accounts/urls.py
from django import views
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    # path('', views.index, name='index'),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("pwupdate/", views.pwupdate, name="change_password"),
    path("delete/", views.delete, name="delete"),
    path("detail/", views.detail, name="detail"),
    path("user_detail/<int:pk>/", views.user_detail, name="user_detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
]

reviews/urls.py
from django.urls import path
from . import views


app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/delete_comment/<int:comment_pk>', views.delete_comment, name='delete_comment')
]

reviews/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings

# Create your models here.
class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    content = models.TextField()
    movie_name = models.CharField(max_length=40)
    grade = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)],
        help_text="0~5사이 값으로 입력하세요",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    view_count = models.IntegerField(default=0)


class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

reviews/forms.py
from django import forms
from .models import Review, Comment

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'content', 'movie_name', 'grade']
        labels = {
            'title':'제목',
            'content':'내용',
            'movie_name':'영화제목',
            'grade':'평점'
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content':'댓글'
        }

reviews/views.py
from django.shortcuts import render, redirect
from .models import Review, Comment
from .forms import ReviewForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.


def index(request):
    reviews = Review.objects.order_by("-pk")
    context = {
        "reviews": reviews,
    }
    return render(request, "reviews/index.html", context)


@login_required
def create(request):
    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            form = review_form.save(commit=False)
            form.user = request.user
            form.save()
            messages.success(request, "작성되었습니다.")
            return redirect("reviews:detail", form.pk)
    else:
        review_form = ReviewForm()
    context = {
        "review_form": review_form,
    }
    return render(request, "reviews/create.html", context)


@login_required
def detail(request, pk):
    review = Review.objects.get(pk=pk)
    stars = []
    for a in range(review.grade):
        stars.append(1)
    empty_stars = []
    for b in range(5 - review.grade):
        empty_stars.append(1)
    review.view_count += 1
    review.save()
    context = {
        "review": review,
        "comment_form": CommentForm(),
        "comments": review.comment_set.all(),
        "stars": stars,
        "empty_stars": empty_stars,
    }
    return render(request, "reviews/detail.html", context)


@login_required
def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.user == review.user:
        if request.method == "POST":
            review_form = ReviewForm(request.POST, instance=review)
            if review_form.is_valid():
                review_user = review_form.save(commit=False)
                review_user.user = request.user
                review_user.save()
                messages.success(request, "수정되었습니다.")
                return redirect("reviews:detail", review.pk)
        else:
            review_form = ReviewForm(instance=review)
        context = {
            "review_form": review_form,
        }
        return render(request, "reviews/update.html", context)
    else:
        messages.warning(request, "작성자만 수정 가능합니다.")
        return redirect("reviews:detail", pk)


@login_required
def delete(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == "POST" and review.user == request.user:
        review.delete()
        return redirect("reviews:index")
    else:
        messages.warning(request, "작성자만 삭제 가능합니다.")
        return redirect("reviews:detail", pk)


@login_required
def create_comment(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.review = review
            comment.save()
            return redirect("reviews:detail", review.pk)


@login_required
def delete_comment(request, review_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == "POST" and comment.user == request.user:
        comment.delete()
    else:
        messages.warning(request, "작성자만 삭제 가능합니다.")
    return redirect("reviews:detail", review_pk)

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1>글 작성</h1>
  <form action="" method='POST'>
    {% csrf_token %}
    {% bootstrap_form review_form %}
    <input class='btn btn-outline-dark' type="submit">
  </form>
{% endblock content %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1 class="">{{ review.pk }}번 게시글</h1>
  <h5>작성자 :
    <a href="{% url 'accounts:user_detail' review.user.pk%}" class="text-decoration-none text-black">
      {{ review.user }}
    </a>
  </h5>
  <h3>{{ review.title }}
    ({{ review.movie_name }})</h3>
  <p>
    {% for star in stars%}
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill text-warning" viewbox="0 0 16 16">
          <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
        </svg>
      </span>
    {% endfor %}
    {% for empty_star in empty_stars %}
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star text-warning" viewbox="0 0 16 16">
          <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
        </svg>
      </span>
    {% endfor %}
  </p>

  <p>{{ review.content }}</p>

  {% if review.user == request.user %}
    <div class="d-flex">
      <a class='btn btn-outline-secondary btn-sm' href="{% url 'reviews:update' review.pk %}">수정</a>
      <button type="button" class="btn btn-outline-danger btn-sm mx-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
        삭제
      </button>
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">삭제하시겠습니까?</h1>
            </div>
            <div class="modal-footer">
              <form class='mx-2' action="{% url 'reviews:delete' review.pk %}" method="POST">
                {% csrf_token %}
                <input class='btn btn-outline-danger btn-sm' type="submit" value="네">
              </form>
              <button type="button" class="btn btn-outline-secondary btn-sm" data-bs-dismiss="modal">아니오</button>
            </div>
          </div>
        </div>
      </div>

    </div>
  {% endif %}

  <hr>
  {% for comment in comments %}
    <div class='d-flex justify-content-between'>
      <p>
        <a href="{% url 'accounts:user_detail' comment.user.pk%}" class="text-decoration-none text-black">
          {{ comment.user }}
        </a>
        |
        <span class='text-secondary' style='font-size:0.8rem;'>{{ comment.created_at }}</span></p>
      {% if comment.user == request.user %}
        <form action="{% url 'reviews:delete_comment' review.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <input class='btn btn-outline-danger btn-sm' type="submit" value="삭제">
        </form>
      {% endif %}
    </div>
    <p>{{ comment.content }}</p>
    <hr>
  {% endfor %}
  <form action="{% url 'reviews:create_comment' review.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form %}

    <input class='btn btn-outline-dark' type="submit" value="OK">
  </form>
{% endblock content %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}

{% block content %}
  <table class="table">
    <thead>
      <tr class="table-primary">
        <th class='text-center  col-2 fs-5' scope="col">영화이름</th>
        <th class='text-center col-3 fs-5' scope="col">리뷰제목</th>
        <th class='text-center col-1 fs-5' scope="col">평점</th>
        <th class='text-center col-2 fs-5' scope="col">작성자</th>
        <th class='text-center col-2 fs-5' scope="col">작성시간</th>
        <th class='text-center col-1 fs-5' scope="col">조회수</th>
        <th class='text-center col-2 fs-5' scope="col"></th>
      </tr>
    </thead>
    <tbody class="table-light">
      {% for review in reviews %}
        <tr>
          <td class='text-center' scope="col">
            <p class='my-0'>{{ review.movie_name }}</p>
          </td>
          <td class='text-center' scope="col">
            <p class='my-0'>{{ review.title }}</p>
          </td>
          <td class='text-center' scope="col">
            <p class='my-0'>{{ review.grade }}
              / 5점</p>
          </td>
          <td class='text-center' scope="col">
            <p class='my-0'>{{ review.user }}</p>
          </td>
          <td class='text-center' scope="col">
            <p class='my-0'>{{ review.created_at | date:'Y-m-d A f' }}</p>
          </td>
          <td class='text-center' scope="col">
            <p class='my-0'>{{ review.view_count }}</p>
          </td>
          <td class='text-center' scope="col">
            <a class='btn btn-outline-dark btn-sm' href="{% url 'reviews:detail' review.pk %}">보기</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<h1>글 수정</h1>
<form action="" method='POST'>
    {% csrf_token %}
    {% bootstrap_form review_form %}
    {% bootstrap_button button_type='submit' content='작성' %}
</form>
{% endblock content %}