accounts/urls.py
from django import views
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    # path('', views.index, name='index'),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("pwupdate/", views.pwupdate, name="change_password"),
    path("delete/", views.delete, name="delete"),
    path("detail/", views.detail, name="detail"),
    path("user_detail/<int:pk>/", views.user_detail, name="user_detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
]

reviews/urls.py
from django.urls import path
from . import views


app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/delete_comment/<int:comment_pk>', views.delete_comment, name='delete_comment')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username',)

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name','last_name','email',)

accounts/views.py
from django.shortcuts import redirect, render
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("reviews:index")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def index(request):
    users = get_user_model().objects.all()
    context = {
        "users": users,
    }
    return render(request, "reviews/index.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "reviews:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect("reviews:index")


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("reviews:detail")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


@login_required
def pwupdate(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("reviews:detail")
    else:
        form = PasswordChangeForm(request.user)
    context = {"form": form}
    return render(request, "accounts/change_password.html", context)


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("reviews:index")


@login_required
def detail(request):
    context = {
        "reviews": request.user.review_set.all(),
        "comments": request.user.comment_set.all(),
    }
    return render(request, "accounts/detail.html", context)


def user_detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        "user": user,
        "reviews": user.review_set.all(),
        "comments": user.comment_set.all(),
    }
    return render(request, "accounts/user_detail.html", context)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <form action="" method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button 'update' %}
  </form>
{% endblock content %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% block content %}

  <h1>{{ user.username }}의 페이지
  </h1>
  <hr>

  <p>first-name :
    {{ user.first_name }}
  </p>

  <p>last-name :
    {{ user.last_name }}
  </p>

  <p>email :
    {{ user.email }}
  </p>

  <a href="{% url 'accounts:update'%}" class='text-decoration-none'>회원정보수정</a>
  <div class='my-5'>
    <h1>작성한 글({{reviews|length}})</h1>
    <hr>
    {% for review in reviews %}
      <div class="d-flex justify-content-between">
        <p>{{ review.title }}</p>
        <div class="d-flex">
          <p class="mx-2">{{ review.created_at }}</p>
          <div>
            <a class='btn btn-outline-dark btn-sm' href="{% url 'reviews:detail' review.pk %}">보기</a>
          </div>
        </div>
      </div>
      <hr>
    {% endfor %}
  </div>
  <div class="my-5">
    <h1>작성한 댓글({{comments|length}})</h1>
    <hr>
    {% for comment in comments %}
      <div class="d-flex justify-content-between">
        <p>{{ comment.content }}</p>
        <div class="d-flex">
          <p class="mx-2">{{ comment.created_at }}</p>
          <div>
            <a class='btn btn-outline-dark btn-sm' href="{% url 'reviews:detail' comment.review_id %}">보기</a>
          </div>
        </div>
      </div>
      <hr>
    {% endfor %}
  </div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <div class='d-flex justify-content-center align-items-center my-5'>
    <div class="text-center border border-black p-5 rounded shadow-lg mb-5 bg-body " style="width : 500px;">
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button 'login' %}
      </form>
    </div>
  </div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

  {% if request.resolver_match.url_name == 'signup' %}
    <h1>Signup</h1>
  {% else %}
    <h1>Update</h1>
  {% endif %}

  <form action="" method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}

    {% if request.resolver_match.url_name == 'signup' %}
      {% bootstrap_button 'signup' %}
    {% else %}
      <a href="{% url 'accounts:change_password'%}" class='text-decoration-none'>비밀번호 변경</a>
      {% bootstrap_button 'update' %}

    {% endif %}
  </form>

{% endblock %}

accounts/templates/accounts/user_detail.html
{% extends 'base.html' %}
{% block content %}

  <h1>{{ user.username }}의 페이지
  </h1>
  <hr>

  <p>first-name :
    {{ user.last_name }}
  </p>

  <p>last-name :
    {{ user.first_name }}
  </p>

  <p>email :
    {{ user.email }}
  </p>

  <div class='my-5'>
    <h2>작성한 글({{reviews|length}})</h2>
    <hr>
    {% for review in reviews %}
      <div class="d-flex justify-content-between">
        <p>{{ review.title }}</p>
        <div class="d-flex">
          <p class="mx-2">{{ review.created_at | date:'Y-m-d A f' }}</p>
          <div>
            <a class='btn btn-outline-dark btn-sm' href="{% url 'reviews:detail' review.pk %}">보기</a>
          </div>
        </div>
      </div>
      <hr>
    {% endfor %}
  </div>
  <div class="my-5">
    <h2>작성한 댓글({{comments|length}})</h2>
    <hr>
    {% for comment in comments %}
      <div class="d-flex justify-content-between">
        <p>{{ comment.content }}</p>
        <div class="d-flex">
          <p class="mx-2">{{ comment.created_at | date:'Y-m-d A f' }}</p>
          <div>
            <a class='btn btn-outline-dark btn-sm' href="{% url 'reviews:detail' comment.review_id %}">보기</a>
          </div>
        </div>
      </div>
      <hr>
    {% endfor %}
  </div>
{% endblock content %}