accounts/urls.py
from django import views
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    # path('', views.index, name='index'),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("pwupdate/", views.pwupdate, name="change_password"),
    path("delete/", views.delete, name="delete"),
    path("detail/", views.detail, name="detail"),
    path("user_detail/<int:pk>/", views.user_detail, name="user_detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
]

reviews/urls.py
from django.urls import path
from . import views


app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/delete_comment/<int:comment_pk>', views.delete_comment, name='delete_comment')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Noto Sans KR', sans-serif;
        background-color: ghostwhite;
      }
    </style>
    {% block css %}{% endblock css %}
  </head>

  <body>
    <header class="d-flex flex-wrap justify-content-center py-3 border-bottom text-dark" style="background-color: #e3f2fd;">
      <ul class="nav nav-pills fs-4">
        <li class="nav-item">
          <a href="{% url 'reviews:index' %}" class="nav-link text-dark">게시판</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'reviews:create' %}" class="nav-link text-dark">작성</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'accounts:detail'%}" class="nav-link text-dark">마이페이지</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'accounts:logout' %}" class="nav-link text-dark">로그아웃</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a href="{% url 'accounts:signup' %}" class="nav-link text-dark">회원가입</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'accounts:login' %}" class="nav-link text-dark">로그인</a>
          </li>
        {% endif %}
      </ul>
    </header>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    <div class="container my-5">
      {% block content %}{% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>

</html>